### ISSUE TITLE
Add support for indoor corridors

### ISSUE THREAD

**Issue by EricRossC** [AndGem/OsmToRoadGraph#58]
Hi!
I'm working in an app to search for the best path between buildings, and one option for walking (besides highways) are indoor corridors.

I did the following modification to include such areas as pedestrian ways:

```
diff --git a/osm/osm_types.py b/osm/osm_types.py
index b70e555..8365dba 100644
--- a/osm/osm_types.py
+++ b/osm/osm_types.py
@@ -1,6 +1,6 @@
 # -*- coding: utf-8 -*-
 class OSMWay:
-    __slots__ = ["osm_id", "nodes", "highway", "area", "max_speed", "direction", "forward", "backward", "name"]
+    __slots__ = ["osm_id", "nodes", "highway", "area", "max_speed", "direction", "forward", "backward", "name", "indoor"]

     def __init__(self, osm_id):
         self.osm_id = osm_id
@@ -22,4 +22,4 @@ class OSMNode(object):

     def __init__(self, osm_id, lat=None, lon=None):
         self.osm_id = osm_id
-        self.lat, self.lon = lat, lon
\ No newline at end of file
+        self.lat, self.lon = lat, lon
diff --git a/osm/way_parser_helper.py b/osm/way_parser_helper.py
index 4ced3bf..c22aa56 100644
--- a/osm/way_parser_helper.py
+++ b/osm/way_parser_helper.py
@@ -8,6 +8,10 @@ class WayParserHelper:
         if way.area == 'yes':
             return False

+        if hasattr(way, "indoor"):
+            if way.indoor == "corridor":
+                return True
+
         if way.highway not in self.config.accepted_highways[self.config.network_type]:
             return False

diff --git a/osm/xml_handler.py b/osm/xml_handler.py
index 2ba6961..f7b1d7b 100644
--- a/osm/xml_handler.py
+++ b/osm/xml_handler.py
@@ -102,6 +102,10 @@ class WayHandler(xml.sax.ContentHandler):
                     elif attributes["k"] == "junction":
                         if attributes["v"] == "roundabout":
                             self.current_way.direction = "oneway"
+                    elif attributes["k"] == "indoor":
+                        if attributes["v"] == "corridor":
+                            self.current_way.indoor = "corridor"
+                            self.current_way.highway = "pedestrian"
             except:
                 e = sys.exc_info()[0]
                 print("Error while parsing: {}".format(e))

```

**Comment by AndGem** [comment]
Hi @EricRossC 

Thanks a lot for the this proposal. It looks good to me, the only thing I was thinking about is people may have different use cases where indoor may be not desirable to have in the network. 

Not sure what the best approach is, but I'll think about it a bit more, and see what I can do. 

But really awesome to hear this project is being used.

If you are interested, I'm currently working on a re-implementation in Rust that is able to handle the binary OSM files and is significantly faster. You can find it here: https://github.com/AndGem/OsmToRoadGraphRust but it's not even with respect to functionality.

Anyway, I'll keep you updated. If you have more proposal, feel free to add them.

**Comment by AndGem** [comment]
@EricRossC 

Actually, everything looks good to me, since the configuration of the considered highway tags is defined somewhere else. Do you want to open a PR or are you ok with me merging you changes directly by myself?

**Comment by AndGem** [comment]
@EricRossC just fyi, I added a change to enable indoor path extraction, but a bit different that in your proposal. I also added an explanation in the README to show how it would work. Please let me know if you have concerns or other proposals. 

Thanks again!

**Comment by EricRossC** [comment]
Thanks!
